application: placeranking
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /rest/opinion
  script: placeranking/opinion.py

- url: /(opinion|home|$)
  script: placeranking/main_webapp.py

- url: /css
  static_dir: public/css

- url: /img
  static_dir: public/img

- url: /js
  static_dir: public/js


#libraries:
#- name: django
#  version: "1.2"
